name: Youtube Music Deployment

on:
  push:
    branches: [  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: auto deploy steps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZURI_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/zuri.chat/zuriplugins/music_plugin/staging/zc_plugin_youtube_music_video/root
            yarn install
            yarn build
            cd ../server/client
            yarn build
            yarn install
            cd ..
            source .venv/bin/activate
            pip3 install -r requirements.txt --upgrade
            python3 manage.py collectstatic --noinput
            pkill -u ${{secrets.USERNAME}} gunicorn
            gunicorn --bind 0.0.0.0:{} config.wsgi --daemon
